--------------------------------------------------------
--  File created - Tuesday-January-05-2021   
--------------------------------------------------------
DROP TABLE "ASUS2"."BONDESCOMMANDES";
DROP TABLE "ASUS2"."EMPLOYEN";
DROP TABLE "ASUS2"."DON";
DROP TABLE "ASUS2"."FAMILLES";
DROP TABLE "ASUS2"."CONGE";
DROP TABLE "ASUS2"."CLIENT";
DROP TABLE "ASUS2"."CHANTIERS";
DROP TABLE "ASUS2"."MATERIAUX_MAINT";
DROP TABLE "ASUS2"."FOURNISSEURS";
DROP TABLE "ASUS2"."MATERIAUX_MANQ";
DROP TABLE "ASUS2"."MATERIAUX_POSS";
DROP TABLE "ASUS2"."PRODUIT";
DROP TABLE "ASUS2"."SALLES";
DROP TABLE "ASUS2"."SOCIETES";
DROP TABLE "ASUS2"."TACHE";
--------------------------------------------------------
--  DDL for Table BONDESCOMMANDES
--------------------------------------------------------

  CREATE TABLE "ASUS2"."BONDESCOMMANDES" 
   (	"TYPE_DE_PRODUIT" VARCHAR2(20 BYTE), 
	"PRIX_TOTAL" NUMBER, 
	"ID_DE_COMMANDE" VARCHAR2(20 BYTE), 
	"MATRICULE_DE_FOURNISSEUR" VARCHAR2(20 BYTE), 
	"LISTE_DE_PRODUIT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEN
--------------------------------------------------------

  CREATE TABLE "ASUS2"."EMPLOYEN" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"SITUATIONFAMILIALE" VARCHAR2(20 BYTE), 
	"FONCTION" VARCHAR2(20 BYTE), 
	"DATENAISS" VARCHAR2(20 BYTE), 
	"ANNEESEXP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DON
--------------------------------------------------------

  CREATE TABLE "ASUS2"."DON" 
   (	"MATRICULE" NUMBER, 
	"SOURCE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"VALEUR" NUMBER, 
	"AUTRE" VARCHAR2(20 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FAMILLES
--------------------------------------------------------

  CREATE TABLE "ASUS2"."FAMILLES" 
   (	"ID" NUMBER, 
	"MATRICULE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"BESOIN" VARCHAR2(20 BYTE), 
	"NBR_MEMBRES" NUMBER, 
	"REGION" VARCHAR2(20 BYTE), 
	"DON" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGE
--------------------------------------------------------

  CREATE TABLE "ASUS2"."CONGE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"NBREJ" VARCHAR2(20 BYTE), 
	"DATECONGE" VARCHAR2(20 BYTE), 
	"TYPECONGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ASUS2"."CLIENT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"DATEM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHANTIERS
--------------------------------------------------------

  CREATE TABLE "ASUS2"."CHANTIERS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"REGIONS" VARCHAR2(20 BYTE), 
	"RUE" VARCHAR2(20 BYTE), 
	"AFFECTATION" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIAUX_MAINT
--------------------------------------------------------

  CREATE TABLE "ASUS2"."MATERIAUX_MAINT" 
   (	"REFERANCE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"REGION" VARCHAR2(20 BYTE), 
	"DATEM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "ASUS2"."FOURNISSEURS" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIAUX_MANQ
--------------------------------------------------------

  CREATE TABLE "ASUS2"."MATERIAUX_MANQ" 
   (	"REFERANCE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER, 
	"DISPO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIAUX_POSS
--------------------------------------------------------

  CREATE TABLE "ASUS2"."MATERIAUX_POSS" 
   (	"REFERANCE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "ASUS2"."PRODUIT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"QUANTITE" VARCHAR2(20 BYTE), 
	"PRIX" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALLES
--------------------------------------------------------

  CREATE TABLE "ASUS2"."SALLES" 
   (	"REF" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE), 
	"DATES" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SOCIETES
--------------------------------------------------------

  CREATE TABLE "ASUS2"."SOCIETES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TACHE
--------------------------------------------------------

  CREATE TABLE "ASUS2"."TACHE" 
   (	"MATRICULE" VARCHAR2(20 BYTE), 
	"IDENTIFIANT" VARCHAR2(20 BYTE), 
	"DEBUT" VARCHAR2(20 BYTE), 
	"FIN" VARCHAR2(20 BYTE), 
	"LIBELLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ASUS2.BONDESCOMMANDES
SET DEFINE OFF;
REM INSERTING into ASUS2.EMPLOYEN
SET DEFINE OFF;
Insert into ASUS2.EMPLOYEN (MATRICULE,NOM,PRENOM,EMAIL,SITUATIONFAMILIALE,FONCTION,DATENAISS,ANNEESEXP) values ('999','ttt','erzaera','zera','Celibataire(e)','Administrateur','3/1/2000','2');
Insert into ASUS2.EMPLOYEN (MATRICULE,NOM,PRENOM,EMAIL,SITUATIONFAMILIALE,FONCTION,DATENAISS,ANNEESEXP) values ('9895','azer','zera','zer','Divorce(e)','Administrateur','2/1/2000','2');
REM INSERTING into ASUS2.DON
SET DEFINE OFF;
Insert into ASUS2.DON (MATRICULE,SOURCE,TYPE,VALEUR,AUTRE,ID) values (0,null,null,0,null,0);
Insert into ASUS2.DON (MATRICULE,SOURCE,TYPE,VALEUR,AUTRE,ID) values (806,'tat','argent',2,'-',806);
Insert into ASUS2.DON (MATRICULE,SOURCE,TYPE,VALEUR,AUTRE,ID) values (989,'aaa','argent',3,'-',989);
Insert into ASUS2.DON (MATRICULE,SOURCE,TYPE,VALEUR,AUTRE,ID) values (908,'aa','argent',2,'-',null);
REM INSERTING into ASUS2.FAMILLES
SET DEFINE OFF;
Insert into ASUS2.FAMILLES (ID,MATRICULE,NOM,BESOIN,NBR_MEMBRES,REGION,DON) values (809,809,'aaa','argent',1,'ee',0);
Insert into ASUS2.FAMILLES (ID,MATRICULE,NOM,BESOIN,NBR_MEMBRES,REGION,DON) values (989,989,'ezr','argent',1,'eee',806);
REM INSERTING into ASUS2.CONGE
SET DEFINE OFF;
Insert into ASUS2.CONGE (MATRICULE,NBREJ,DATECONGE,TYPECONGE) values ('9895','2','1/1/2000','fetes');
REM INSERTING into ASUS2.CLIENT
SET DEFINE OFF;
Insert into ASUS2.CLIENT (NOM,PRENOM,CIN,DATEM) values ('tttttt','test','808080','Wed Mar 1 2000');
REM INSERTING into ASUS2.CHANTIERS
SET DEFINE OFF;
Insert into ASUS2.CHANTIERS (ID,NOM,REGIONS,RUE,AFFECTATION,ETAT) values ('9008','tata','Region sud','eee','tttt','En cours');
Insert into ASUS2.CHANTIERS (ID,NOM,REGIONS,RUE,AFFECTATION,ETAT) values (null,null,'Region sud',null,'tttt','En cours');
Insert into ASUS2.CHANTIERS (ID,NOM,REGIONS,RUE,AFFECTATION,ETAT) values (null,null,'Region sud',null,'tttt','En cours');
Insert into ASUS2.CHANTIERS (ID,NOM,REGIONS,RUE,AFFECTATION,ETAT) values (null,null,'Region sud',null,'tttt','En cours');
Insert into ASUS2.CHANTIERS (ID,NOM,REGIONS,RUE,AFFECTATION,ETAT) values (null,null,'Region sud',null,'tttt','En cours');
Insert into ASUS2.CHANTIERS (ID,NOM,REGIONS,RUE,AFFECTATION,ETAT) values ('985','pppp','Region sud','sdfdfg','zerz','En cours');
REM INSERTING into ASUS2.MATERIAUX_MAINT
SET DEFINE OFF;
Insert into ASUS2.MATERIAUX_MAINT (REFERANCE,NOM,REGION,DATEM) values (999,'nabeul','test','1/1/2000 12:00 AM');
REM INSERTING into ASUS2.FOURNISSEURS
SET DEFINE OFF;
REM INSERTING into ASUS2.MATERIAUX_MANQ
SET DEFINE OFF;
REM INSERTING into ASUS2.MATERIAUX_POSS
SET DEFINE OFF;
Insert into ASUS2.MATERIAUX_POSS (REFERANCE,NOM,ETAT) values (809,'ee','mauvaise etat ');
REM INSERTING into ASUS2.PRODUIT
SET DEFINE OFF;
Insert into ASUS2.PRODUIT (NOM,REFERENCE,QUANTITE,PRIX) values ('test','102','rar','90');
REM INSERTING into ASUS2.SALLES
SET DEFINE OFF;
REM INSERTING into ASUS2.SOCIETES
SET DEFINE OFF;
Insert into ASUS2.SOCIETES (ID,NOM) values ('908','pppp');
Insert into ASUS2.SOCIETES (ID,NOM) values ('98987','tazer');
REM INSERTING into ASUS2.TACHE
SET DEFINE OFF;
